name: octo
dependencies:
  - python=3.9
  - pip=21.1
  - psycopg2=2.8
  - pip:
      - django==3.2
      - djangorestframework==3.12
      - djangorestframework-simplejwt==4.7
      - gunicorn==20.1
      - pillow==8.2
      - flake8==3.9
      - django-cors-headers
      - drf-yasg==1.20
